# Loading libraries
require(dplyr)
require(magrittr)
require(reshape2)
# Loading datasets
source("df.R")
genera_db<-function(df,x,y){
df%>%filter(Perturbación==x)->pp
pp_d<-dcast(pp, Tipo_de_permanencia~Riqueza+Manejo, value.var=y,fun.aggregate=function(x)mean(x))
pp_n<-as.matrix(pp_d[,2:21])
pp_n0<-ifelse(is.finite(pp_n),pp_n,0)
rownames(pp_n0)<-levels(df$Tipo_de_permanencia)
colnames(pp_n0)<-c("MFC-D", "MFC-DI", "MFC-H", "MFC-HI", "MF-D", "MF-DI", "MF-H", "MF-HI", "MC-D", "MC-DI", "MC-H", "MC-HI", "M-D", "M-DI", "M-H", "M-HI", "C-D", "C-DI", "C-H", "C-HI")
return(pp_n0)
}
sequia<-genera_db(df,"Sequía", "Permanencia_promedio")
arvenses<-genera_db(df,"Arvenses", "Permanencia_promedio")
herbivoros<-genera_db(df,"Herbívoros", "Permanencia_promedio")

png("barras.png", height=11, width=8, units="in", res=300)
par(cex=2,mfrow=c(3,1))
barplot(herbivoros, ylim=c(0,0.7), beside=T, col=c("light green", "dark green", "yellow", "red", "violet"), border="purple", ylab="\nPermanencia",main="a) Permanencias promedio individuales y conjuntas ante la influencia de los herbívoros",xaxt="n", legend.text=T)
abline(a=mean(df$Permanencia_promedio),b=0, lty=1)
abline(a=median(df$Permanencia_promedio),b=0, lty=2)
abline(a=mean(herbivoros),b=0, lty=1,col="blue")
abline(a=median(herbivoros),b=0, lty=2,col="blue")
abline(v=24.5,lwd=1.5)
abline(v=48.5,lwd=1.5)
abline(v=72.5,lwd=1.5)
abline(v=96.5,lwd=1.5)

barplot(sequia, ylim=c(0,0.7), beside=T, col=c("light green", "dark green", "yellow", "red", "violet"), border="purple", ylab="\nPermanencia",main="b) Permanencias promedio individuales y conjuntas ante un escenario de sequía", xaxt="n")
abline(a=mean(df$Permanencia_promedio),b=0, lty=1)
abline(a=median(df$Permanencia_promedio),b=0, lty=2)
abline(a=mean(sequia),b=0, lty=1,col="red")
abline(a=median(sequia),b=0, lty=2,col="red")
#abline(v=4,col="blue")
abline(v=24.5,lwd=1.5)
abline(v=48.5,lwd=1.5)
abline(v=72.5,lwd=1.5)
abline(v=96.5,lwd=1.5)

barplot(arvenses, ylim=c(0,0.7), beside=T, col=c("light green", "dark green", "yellow", "red", "violet"), border="purple", ylab="\nPermanencia",main="c) Permanencias promedio individuales y conjuntas ante la influencia de las arvenses", las=2)
abline(a=mean(df$Permanencia_promedio),b=0, lty=1)
abline(a=median(df$Permanencia_promedio),b=0, lty=2)
abline(a=mean(arvenses),b=0, lty=1,col="dark green")
abline(a=median(arvenses),b=0, lty=2,col="dark green")
abline(v=24.5,lwd=1.5)
abline(v=48.5,lwd=1.5)
abline(v=72.5,lwd=1.5)
abline(v=96.5,lwd=1.5)

dev.off()

#png("barras_herbivoros.png", height=800, width=1200)
#par(cex=1.5)
#barplot(herbivoros, ylim=c(0,1), beside=T, col=c("light green", "dark green", "yellow", "red", "violet"), border="purple", ylab="\nPermanencia",main="Permanencias promedio individuales y conjuntas ante la influencia de los herbívoros",xaxt="n", legend.text=T)
#abline(a=mean(df$Permanencia_promedio),b=0, lty=4)
#dev.off()	

#png("barras_sequia.png", height=800, width=1200)
#par(cex=1.5)
#barplot(sequia, ylim=c(0,1), beside=T, col=c("light green", "dark green", "yellow", "red", "violet"), border="purple", ylab="\nPermanencia",main="Permanencias promedio individuales y conjuntas ante un escenario de sequía", xaxt="n")
#abline(a=mean(df$Permanencia_promedio),b=0, lty=4)
#dev.off()

#png("barras_arvenses.png", height=800, width=1200)
#par(cex=1.5, mar = c(18,4,4,2) + 0.1)
#barplot(arvenses, ylim=c(0,1), beside=T, col=c("light green", "dark green", "yellow", "red", "violet"), border="purple", ylab="\nPermanencia",main="Permanencias promedio individuales y conjuntas ante la influencia de las arvenses", las=2)
#abline(a=mean(df$Permanencia_promedio),b=0, lty=4)
#dev.off()
